export const GET_SHIVANI_STATE = 'GET_SHIVANI_STATE';
export const GET_YASH_STATE = 'GET_YASH_STATE';

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';
